-- Thêm dữ liệu cho bảng provinces
INSERT INTO province (province_name) VALUES 
-- Thành phố trực thuộc trung ương
('Hà Nội'),
('Hồ Chí Minh'),
('Hải Phòng'),
('Đà Nẵng'),
('Cần Thơ'),

-- Các tỉnh miền Bắc
('Hà Giang'),
('Cao Bằng'),
('Bắc Kạn'),
('Tuyên Quang'),
('Lào Cai'),
('Điện Biên'),
('Lai Châu'),
('Sơn La'),
('Yên Bái'),
('Hoà Bình'),
('Thái Nguyên'),
('Lạng Sơn'),
('Quảng Ninh'),
('Bắc Giang'),
('Phú Thọ'),
('Vĩnh Phúc'),
('Bắc Ninh'),
('Hải Dương'),
('Hưng Yên'),
('Thái Bình'),
('Hà Nam'),
('Nam Định'),
('Ninh Bình'),

-- Các tỉnh miền Trung
('Thanh Hóa'),
('Nghệ An'),
('Hà Tĩnh'),
('Quảng Bình'),
('Quảng Trị'),
('Thừa Thiên Huế'),
('Quảng Nam'),
('Quảng Ngãi'),
('Bình Định'),
('Phú Yên'),
('Khánh Hòa'),
('Ninh Thuận'),
('Bình Thuận'),

-- Các tỉnh Tây Nguyên
('Kon Tum'),
('Gia Lai'),
('Đắk Lắk'),
('Đắk Nông'),
('Lâm Đồng'),

-- Các tỉnh miền Nam
('Bình Phước'),
('Tây Ninh'),
('Bình Dương'),
('Đồng Nai'),
('Bà Rịa - Vũng Tàu'),
('Long An'),
('Tiền Giang'),
('Bến Tre'),
('Trà Vinh'),
('Vĩnh Long'),
('Đồng Tháp'),
('An Giang'),
('Kiên Giang'),
('Hậu Giang'),
('Sóc Trăng'),
('Bạc Liêu'),
('Cà Mau');
